# Project information
site_name: David Arnaiz
site_url: https://electronplant.github.io/personal-page/
repo_name: personal-page
repo_url: https://github.com/ElectronPlant/personal-page
site_description: >-
  Embedded Firmware Engineer specializing in adaptive IoT sensors, RTOS, and dynamic energy management for low-power devices. Portfolio of David Arnaiz.

# Copyright
copyright: Copyright Â© 2026 David Arnaiz

# Configuration
theme:
  name: material
  language: en
  logo: assets/imgs/test_icon.png
  favicon: assets/imgs/test_icon.png
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.footer

  palette:
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra_css:
    - extra_style.css

extra_templates:
    - google009ed8c895b10d28.html

extra:
  social:
    - icon: octicons/mail-16
      link: mailto://electronplant@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/ElectronPlant
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/david-arnaiz-mart%C3%ADnez
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com/citations?user=32m35KwAAAAJ&hl=en

markdown_extensions:
  - attr_list:
  - md_in_html:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
    - search:
    - blog:

nav:
    - Profile: index.md
    - Research:
        - research/research.md
        - research/thesis.md
    - Projects:
        - projects/projects.md
    # - Blog:
    #     - blog/index.md
    - info: info/info.md

